export const projects = [
  {
    id: 1,
    title: "The Power of Web Development",
    category: "Design",
    image: "assets/images/project-2.jpg",
    description: "Learn about how web development transforms industries.",
  },
  {
    id: 2,
    title: "Emerging IT Technologies",
    category: "Technology",
    image: "assets/images/project-3.jpg",
    description: "Discover the latest IT trends shaping the future.",
  },
  {
    id: 3,
    title: "Innovative Business Ideas",
    category: "Business",
    image: "assets/images/project-4.jpg",
    description: "Explore groundbreaking ideas driving businesses forward.",
  },
  {
    id: 4,
    title: "Branding the Digital Age",
    category: "Tech App",
    image: "assets/images/project-1.jpg",
    description: "Explore groundbreaking ideas driving businesses forward.",
  },
  {
    id: 5,
    title: "Hybrid & Native Apps",
    category: "Hybrid Apps",
    image: "assets/images/project-2.jpg",
    description: "Explore groundbreaking ideas driving businesses forward.",
  },
  {
    id: 6,
    title: "Technology & Innovation",
    category: "Innovation",
    image: "assets/images/project-3.jpg",
    description: "Explore groundbreaking ideas driving businesses forward.",
  },
  {
    id: 7,
    title: "IT Consultancy Services",
    category: "IT Consultancy",
    image: "assets/images/project-4.jpg",
    description: "Explore groundbreaking ideas driving businesses forward.",
  },
  {
    id: 8,
    title: "Multitasking on new features",
    category: "Multitasking",
    image: "assets/images/project-1.jpg",
    description: "Explore groundbreaking ideas driving businesses forward.",
  },
  {
    id: 9,
    title: "Quick IT Support",
    category: "Quick Support",
    image: "assets/images/project-2.jpg",
    description: "Explore groundbreaking ideas driving businesses forward.",
  },
  {
    id: 10,
    title: "Companies branding",
    category: "Branding",
    image: "assets/images/project-3.jpg",
    description: "Explore groundbreaking ideas driving businesses forward.",
  },
];
